Attribute VB_Name = "UzLotinKirill"
' =====================================================================
'  Lotin <-> Kirill (O'zbek) for Microsoft Word - Mac and Windows.
'  Works fully offline. Same rules and dictionary as the Word add-in
'  (https://github.com/abdullohukr/uz-lotin-kirill).
'
'  Macros:
'    UzKirillga  - selection (or the whole document) to Cyrillic
'    UzLotinga   - selection (or the whole document) to Latin
'    UzLugat     - open my dictionary (lotin = kirill, one per line)
'    UzSelfTest  - check that this module works correctly
'
'  Only letters are changed. Quotes, punctuation and formatting stay.
'  This file is GENERATED by tools/build_vba.js - edit the template.
' =====================================================================
Option Explicit

' Apostrophes in Latin output:
'   1 = o' and ma'no with U+2018 / U+2019 (typographic)
'   2 = U+02BB / U+02BC (official)
'   3 = plain '
Private Const APOS_STYLE As Long = 1
Private Const LUGAT_FILE As String = "UzLotinKirill-lugat.docx"
Private Const CODES As String = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@"

Private gLoaded As Boolean
Private gL2C As Collection, gL2CStem As Collection
Private gC2L As Collection, gC2LStem As Collection
Private gUL2C As Collection, gUC2L As Collection, gSkip As Collection
Private gMaxL2C As Long, gMaxC2L As Long
Private gLugatStamp As String
Private gTestN As Long, gTestFail As Long, gTestMsg As String

Private OK As String, TQ As String, gOkina As String, gTutuq As String
Private APOS As String, CYRSET As String, CYRV As String
Private LATSRC As String, LATDST As String, CYRSRC As String, CYRDST As Variant
' single Cyrillic letters used by the rules
Private cA As String, cS As String, cHh As String, cSh As String, cCh As String
Private cU As String, cGh As String, cYo As String, cYu As String, cYa As String
Private cYe As String, cE As String, cTs As String, cHard As String, cSoft As String
Private cM As String

' ============================== public macros

Public Sub UzKirillga()
    RunConvert False
End Sub

Public Sub UzLotinga()
    RunConvert True
End Sub

Public Sub UzLugat()
    Dim p As String, d As Document
    LoadAll
    p = LugatPath()
    If Len(Dir(p)) = 0 Then
        Set d = Documents.Add
        d.Content.Text = "# Mening lug'atim. Har qatorda: lotin = kirill" & vbCr & _
            "# O'girilmaydigan so'zni yolg'iz yozing (masalan: iPhone)." & vbCr & _
            "# Qator boshida # bo'lsa, u hisobga olinmaydi." & vbCr & _
            UDec("Hiraql = {04B2}{0438}{0440}{0430}{049B}{043B}") & vbCr
        d.SaveAs FileName:=p, FileFormat:=wdFormatXMLDocument
    Else
        For Each d In Documents
            If d.FullName = p Then d.Activate: Exit Sub
        Next d
        Documents.Open FileName:=p
    End If
End Sub

Public Sub UzSelfTest()
    Dim saveO As String, saveT As String, saveU1 As Collection, saveU2 As Collection, saveS As Collection
    LoadAll
    saveO = gOkina: saveT = gTutuq
    Set saveU1 = gUL2C: Set saveU2 = gUC2L: Set saveS = gSkip
    gOkina = ChrW(&H2018): gTutuq = ChrW(&H2019)
    Set gUL2C = New Collection: Set gUC2L = New Collection: Set gSkip = New Collection
    gTestN = 0: gTestFail = 0: gTestMsg = ""
    RunTests
    gOkina = saveO: gTutuq = saveT
    Set gUL2C = saveU1: Set gUC2L = saveU2: Set gSkip = saveS
    If gTestFail = 0 Then
        MsgBox "Hammasi to'g'ri: " & gTestN & " / " & gTestN, vbInformation, "Lotin-Kirill"
    Else
        MsgBox "Xatolar: " & gTestFail & " / " & gTestN & vbCr & vbCr & Left$(gTestMsg, 900), vbExclamation, "Lotin-Kirill"
    End If
End Sub

' ============================== document conversion

Private Sub RunConvert(ByVal toLat As Boolean)
    Dim nW As Long, nS As Long, st As Range, useSel As Boolean, t0 As Single, msg As String
    If Documents.Count = 0 Then Exit Sub
    On Error GoTo Fail
    LoadAll
    t0 = Timer
    useSel = (Selection.End > Selection.Start)
    If useSel Then useSel = (Len(Trim$(Replace(Selection.Text, vbCr, ""))) > 0)
    Application.ScreenUpdating = False
#If Mac Then
#Else
    Application.UndoRecord.StartCustomRecord "Lotin-Kirill"
#End If
    If useSel Then
        ConvertRange Selection.Range, toLat, True, nW, nS
    Else
        For Each st In ActiveDocument.StoryRanges
            Do While Not st Is Nothing
                ConvertRange st, toLat, False, nW, nS
                Set st = st.NextStoryRange
            Loop
        Next st
    End If
Done:
    On Error Resume Next
#If Mac Then
#Else
    Application.UndoRecord.EndCustomRecord
#End If
    Application.ScreenUpdating = True
    Application.StatusBar = ""
    On Error GoTo 0
    If Len(msg) > 0 Then MsgBox msg, vbExclamation, "Lotin-Kirill": Exit Sub
    msg = "Tayyor: " & nW & " ta so'z o'girildi (" & IIf(useSel, "belgilangan matn", "butun hujjat") & _
        ", " & Format$(Timer - t0, "0") & " s)."
    If nS > 0 Then msg = msg & vbCr & nS & " ta so'z maydon (field) ichida bo'lgani uchun o'tkazib yuborildi."
    MsgBox msg, vbInformation, "Lotin-Kirill"
    Exit Sub
Fail:
    msg = "Xato: " & Err.Description
    Resume Done
End Sub

Private Sub ConvertRange(ByVal rng As Range, ByVal toLat As Boolean, ByVal clip As Boolean, _
                         ByRef nWords As Long, ByRef nSkipped As Long)
    Dim para As Paragraph, pr As Range, r As Range, t As String
    Dim starts() As Long, lens() As Long, cnt As Long, k As Long
    Dim tok As String, outS As String, a As Long, b As Long, np As Long, mask As String
    For Each para In rng.Paragraphs
        Set pr = para.Range
        t = pr.Text
        If HasSource(t, toLat) Then
            cnt = Tokenize(t, toLat, starts, lens)
            mask = UrlMask(t)
            For k = cnt To 1 Step -1
                If InStr(1, Mid$(mask, starts(k), lens(k)), "1", vbBinaryCompare) > 0 Then GoTo NextTok
                tok = Mid$(t, starts(k), lens(k))
                If toLat Then outS = WordToLat(tok) Else outS = WordToCyr(tok)
                If StrComp(outS, tok, vbBinaryCompare) <> 0 Then
                    a = pr.Start + starts(k) - 1
                    b = a + lens(k)
                    If (Not clip) Or (a >= rng.Start And b <= rng.End) Then
                        Set r = pr.Duplicate
                        r.SetRange a, b
                        If StrComp(r.Text, tok, vbBinaryCompare) = 0 Then
                            ' Replace through Find: assigning r.Text makes Word mark new
                            ' Cyrillic as East Asian (wide Japanese/Chinese font) in
                            ' documents whose East Asian language is set; Find/Replace does not.
                            If ReplaceInRange(r, tok, outS) Then
                                nWords = nWords + 1
                            Else
                                nSkipped = nSkipped + 1
                            End If
                        Else
                            nSkipped = nSkipped + 1
                        End If
                    End If
                End If
NextTok:
            Next k
        End If
        np = np + 1
        If np Mod 50 = 0 Then
            On Error Resume Next
            Application.StatusBar = "Lotin-Kirill: " & nWords & " ta so'z..."
            On Error GoTo 0
            DoEvents
        End If
    Next para
End Sub

Private Function ReplaceInRange(ByVal r As Range, ByVal findS As String, ByVal repl As String) As Boolean
    With r.Find
        .ClearFormatting
        .Replacement.ClearFormatting
        .Text = findS
        .Replacement.Text = repl
        .Forward = True
        .Wrap = wdFindStop
        .Format = False
        .MatchCase = True
        .MatchWholeWord = False
        .MatchWildcards = False
        .MatchSoundsLike = False
        .MatchAllWordForms = False
        ReplaceInRange = .Execute(Replace:=wdReplaceOne)
    End With
End Function

' "1" for every character that belongs to a link (http://, https://, www.) or an e-mail.
Private Function UrlMask(ByVal t As String) As String
    Dim m As String, i As Long, j As Long, L As Long, low As String, ch As String
    L = Len(t)
    m = String$(L, "0")
    low = LCase$(t)
    i = 1
    Do While i <= L
        If Mid$(low, i, 7) = "http://" Or Mid$(low, i, 8) = "https://" Or Mid$(low, i, 6) = "ftp://" Or Mid$(low, i, 4) = "www." Then
            j = i
            Do While j <= L
                ch = Mid$(t, j, 1)
                If ch = " " Or ch = vbCr Or ch = vbTab Or ch = vbLf Or ch = "<" Or ch = ">" Or ch = """" Or _
                   AscW(ch) = &HAB Or AscW(ch) = &HBB Or AscW(ch) = &H201C Or AscW(ch) = &H201D Or AscW(ch) = &HA0 Then Exit Do
                j = j + 1
            Loop
            Mid$(m, i, j - i) = String$(j - i, "1")
            i = j
        ElseIf Mid$(t, i, 1) = "@" Then
            j = i
            Do While j > 1
                If Not IsMailCh(Mid$(t, j - 1, 1)) Then Exit Do
                j = j - 1
            Loop
            Do While i < L
                If Not IsMailCh(Mid$(t, i + 1, 1)) Then Exit Do
                i = i + 1
            Loop
            Mid$(m, j, i - j + 1) = String$(i - j + 1, "1")
            i = i + 1
        Else
            i = i + 1
        End If
    Loop
    UrlMask = m
End Function

Private Function IsMailCh(ByVal ch As String) As Boolean
    If Len(ch) = 0 Then Exit Function
    IsMailCh = IsLatCh(ch) Or (ch >= "0" And ch <= "9") Or InStr(1, "._%+-", ch, vbBinaryCompare) > 0
End Function

Private Function HasSource(ByVal t As String, ByVal toLat As Boolean) As Boolean
    Dim i As Long, ch As String
    For i = 1 To Len(t)
        ch = Mid$(t, i, 1)
        If toLat Then
            If IsCyrCh(ch) Then HasSource = True: Exit Function
        Else
            If IsLatCh(ch) Then HasSource = True: Exit Function
        End If
    Next i
End Function

' Finds source-script words. Latin words include an apostrophe that is followed
' by a letter or that directly follows o/g (o', tog'). Returns the count.
Private Function Tokenize(ByVal t As String, ByVal toLat As Boolean, starts() As Long, lens() As Long) As Long
    Dim i As Long, j As Long, n As Long, L As Long, ch As String, nx As String, cur As String
    L = Len(t)
    ReDim starts(1 To 16): ReDim lens(1 To 16)
    i = 1
    Do While i <= L
        ch = Mid$(t, i, 1)
        If toLat And IsCyrCh(ch) Then
            j = i
            Do While j < L
                If Not IsCyrCh(Mid$(t, j + 1, 1)) Then Exit Do
                j = j + 1
            Loop
        ElseIf (Not toLat) And IsLatCh(ch) Then
            j = i
            Do While j < L
                nx = Mid$(t, j + 1, 1)
                cur = Mid$(t, j, 1)
                If IsLatCh(nx) Then
                    j = j + 1
                ElseIf IsApos(nx) And (IsLatCh(Mid$(t, j + 2, 1)) Or InStr(1, "oOgG", cur, vbBinaryCompare) > 0) Then
                    j = j + 1
                Else
                    Exit Do
                End If
            Loop
        Else
            j = 0
        End If
        If j > 0 Then
            n = n + 1
            If n > UBound(starts) Then
                ReDim Preserve starts(1 To n * 2): ReDim Preserve lens(1 To n * 2)
            End If
            starts(n) = i: lens(n) = j - i + 1
            i = j + 1
        Else
            i = i + 1
        End If
    Loop
    Tokenize = n
End Function

' Converts a plain string (used by the self test).
Private Function ConvertText(ByVal s As String, ByVal toLat As Boolean) As String
    Dim starts() As Long, lens() As Long, cnt As Long, k As Long, tok As String, outS As String
    Dim mask As String
    cnt = Tokenize(s, toLat, starts, lens)
    mask = UrlMask(s)
    For k = cnt To 1 Step -1
        If InStr(1, Mid$(mask, starts(k), lens(k)), "1", vbBinaryCompare) = 0 Then
            tok = Mid$(s, starts(k), lens(k))
            If toLat Then outS = WordToLat(tok) Else outS = WordToCyr(tok)
            s = Left$(s, starts(k) - 1) & outS & Mid$(s, starts(k) + lens(k))
        End If
    Next k
    ConvertText = s
End Function

' ============================== words

Private Function WordToCyr(ByVal w As String) As String
    Dim norm As String, key As String, pat As Long, v As String, L As Long, maxL As Long
    If IsForeign(w) Or IsRoman(w) Then WordToCyr = w: Exit Function
    norm = NormLatin(w)
    key = LatKey(norm)
    If CHas(gSkip, "L" & key) Then WordToCyr = w: Exit Function
    pat = CasePattern(w)
    If CGet(gUL2C, key, v) Then WordToCyr = ApplyCase(pat, v): Exit Function
    If CGet(gL2C, key, v) Then WordToCyr = ApplyCase(pat, v): Exit Function
    maxL = gMaxL2C
    If Len(key) < maxL Then maxL = Len(key)
    For L = maxL To 3 Step -1
        If CGet(gL2CStem, Left$(key, L), v) Then
            If pat = 2 Then
                v = UC(v)
            ElseIf IsUpperCh(Left$(w, 1)) Then
                v = ApplyCase(1, v)
            End If
            WordToCyr = v & LatRules(norm, L)
            Exit Function
        End If
    Next L
    WordToCyr = LatRules(norm, 0)
End Function

Private Function WordToLat(ByVal w As String) As String
    Dim key As String, pat As Long, v As String, L As Long, maxL As Long
    key = LC(w)
    If CHas(gSkip, "C" & Enc(key)) Then WordToLat = w: Exit Function
    pat = CasePattern(w)
    If CGet(gUC2L, Enc(key), v) Then WordToLat = ApplyCase(pat, FixApos(v)): Exit Function
    If CGet(gC2L, Enc(key), v) Then WordToLat = ApplyCase(pat, FixApos(v)): Exit Function
    maxL = gMaxC2L
    If Len(key) < maxL Then maxL = Len(key)
    For L = maxL To 3 Step -1
        If CGet(gC2LStem, Enc(Left$(key, L)), v) Then
            v = FixApos(v)
            If pat = 2 Then
                v = UC(v)
            ElseIf IsUpperCh(Left$(w, 1)) Then
                v = ApplyCase(1, v)
            End If
            WordToLat = v & CyrRules(w, L)
            Exit Function
        End If
    Next L
    WordToLat = CyrRules(w, 0)
End Function

' Latin -> Cyrillic rules. w is normalised (OK / TQ apostrophes).
Private Function LatRules(ByVal w As String, ByVal startAt As Long) As String
    Dim lw As String, allUp As Boolean, o As String, i As Long, k As Long
    Dim c As String, n As String, n2 As String, n3 As String, p As String
    Dim atStart As Boolean, surname As Boolean, rest As String, hit As Boolean
    lw = LC(w)
    allUp = (CasePattern(w) = 2)
    i = startAt + 1
    Do While i <= Len(lw)
        c = Mid$(lw, i, 1): n = Mid$(lw, i + 1, 1): n2 = Mid$(lw, i + 2, 1): n3 = Mid$(lw, i + 3, 1)
        If i > 1 Then p = Mid$(lw, i - 1, 1) Else p = ""
        atStart = (i = 1)
        hit = True
        If c = "s" And n = TQ And n2 = "h" Then
            o = o & Em(cS & cHh, w, i, allUp): i = i + 3
        ElseIf c = "s" And n = "h" Then
            o = o & Em(cSh, w, i, allUp): i = i + 2
        ElseIf c = "c" And n = "h" Then
            o = o & Em(cCh, w, i, allUp): i = i + 2
        ElseIf c = "o" And n = OK Then
            o = o & Em(cU, w, i, allUp): i = i + 2
        ElseIf c = "g" And n = OK Then
            o = o & Em(cGh, w, i, allUp): i = i + 2
        ElseIf c = "y" And n = "o" And n2 <> OK Then
            o = o & Em(cYo, w, i, allUp): i = i + 2
        ElseIf c = "y" And n = "u" Then
            o = o & Em(cYu, w, i, allUp): i = i + 2
        ElseIf c = "y" And n = "a" Then
            o = o & Em(cYa, w, i, allUp): i = i + 2
        ElseIf c = "y" And n = "e" And (atStart Or LatV(p) Or p = OK Or p = TQ) Then
            o = o & Em(cYe, w, i, allUp): i = i + 2
        ElseIf c = "t" And n = "s" And (Mid$(lw, i + 2, 3) = "iya" Or Mid$(lw, i + 2, 3) = "ion") Then
            o = o & Em(cTs, w, i, allUp): i = i + 2
        ElseIf c = "e" Then
            ' surnames: Abdullaev, Tillaeva -> ev; mikroevolyutsiya keeps e
            surname = (p = "a" Or p = "o" Or p = "u") And n = "v" And Not (n2 = "o" Or n2 = "e" Or n2 = "u")
            If (atStart Or LatV(p)) And Not surname Then
                o = o & Em(cE, w, i, allUp)
            Else
                o = o & Em(cYe, w, i, allUp)
            End If
            i = i + 1
        ElseIf atStart And c = "m" And n = "o" And n2 = OK And (n3 = "j" Or n3 = "t") Then
            ' mo'jiza, mo'tabar -> mu'j, mu't (with hard sign)
            o = o & Em(cM, w, i, allUp) & Em(cU & cHard, w, i + 1, allUp): i = i + 3
        ElseIf c = TQ Or c = OK Then
            If allUp Then o = o & UC(cHard) Else o = o & cHard
            i = i + 1
        Else
            hit = False
        End If
        If Not hit Then
            k = InStr(1, LATSRC, c, vbBinaryCompare)
            If k > 0 And Len(c) > 0 Then
                o = o & Em(Mid$(LATDST, k, 1), w, i, allUp)
            Else
                o = o & Mid$(w, i, 1)
            End If
            i = i + 1
        End If
    Loop
    LatRules = o
End Function

Private Function Em(ByVal cyr As String, ByVal w As String, ByVal idx As Long, ByVal allUp As Boolean) As String
    If allUp Or IsUpperCh(Mid$(w, idx, 1)) Then Em = UC(cyr) Else Em = cyr
End Function

' Cyrillic -> Latin rules.
Private Function CyrRules(ByVal w As String, ByVal startAt As Long) As String
    Dim lw As String, allUp As Boolean, o As String, i As Long, k As Long
    Dim c As String, n As String, p As String, atStart As Boolean
    lw = LC(w)
    allUp = (CasePattern(w) = 2)
    i = startAt + 1
    Do While i <= Len(lw)
        c = Mid$(lw, i, 1): n = Mid$(lw, i + 1, 1)
        If i > 1 Then p = Mid$(lw, i - 1, 1) Else p = ""
        atStart = (i = 1)
        If c = cS And n = cHh Then
            o = o & Lt("s" & gTutuq & "h", w, i, allUp): i = i + 2
        ElseIf c = cU Then
            o = o & Lt("o" & gOkina, w, i, allUp)
            If n = cHard Then i = i + 2 Else i = i + 1
        ElseIf c = cGh Then
            o = o & Lt("g" & gOkina, w, i, allUp)
            If n = cHard Then i = i + 2 Else i = i + 1
        ElseIf c = cYe Then
            If atStart Or CyrVw(p) Or p = cHard Or p = cSoft Then
                o = o & Lt("ye", w, i, allUp)
            Else
                o = o & Lt("e", w, i, allUp)
            End If
            i = i + 1
        ElseIf c = cTs Then
            If CyrVw(p) Then o = o & Lt("ts", w, i, allUp) Else o = o & Lt("s", w, i, allUp)
            i = i + 1
        ElseIf c = cHard Then
            ' object -> obyekt: hard sign after a consonant before ye/yo/yu/ya is dropped
            If (n = cYe Or n = cYo Or n = cYu Or n = cYa) And Len(p) > 0 And Not CyrVw(p) Then
                ' dropped
            Else
                o = o & gTutuq
            End If
            i = i + 1
        Else
            k = 0
            If Len(c) > 0 Then k = InStr(1, CYRSRC, c, vbBinaryCompare)
            If k > 0 Then
                o = o & Lt(CStr(CYRDST(k - 1)), w, i, allUp)
            Else
                o = o & Mid$(w, i, 1)
            End If
            i = i + 1
        End If
    Loop
    CyrRules = o
End Function

Private Function Lt(ByVal lat As String, ByVal w As String, ByVal idx As Long, ByVal allUp As Boolean) As String
    Dim nx As String
    If allUp Then
        Lt = UC(lat)
    ElseIf IsUpperCh(Mid$(w, idx, 1)) Then
        nx = Mid$(w, idx + 1, 1)
        If IsUpperCh(nx) Then
            Lt = UC(lat)
        Else
            Lt = UC(Left$(lat, 1)) & Mid$(lat, 2)
        End If
    Else
        Lt = lat
    End If
End Function

' ============================== helpers

Private Function NormLatin(ByVal w As String) As String
    Dim i As Long, ch As String, p As String, r As String
    For i = 1 To Len(w)
        ch = Mid$(w, i, 1)
        If IsApos(ch) Then
            If i > 1 Then p = Mid$(w, i - 1, 1) Else p = ""
            If Len(p) > 0 And InStr(1, "oOgG", p, vbBinaryCompare) > 0 Then r = r & OK Else r = r & TQ
        Else
            r = r & ch
        End If
    Next i
    NormLatin = r
End Function

' Collection keys: lowercase, apostrophes as "_" (Collection compares keys loosely).
Private Function LatKey(ByVal norm As String) As String
    LatKey = Replace(Replace(LC(norm), OK, "_"), TQ, "_")
End Function

Private Function FixApos(ByVal s As String) As String
    Dim i As Long, ch As String, p As String, r As String
    For i = 1 To Len(s)
        ch = Mid$(s, i, 1)
        If IsApos(ch) Then
            If i > 1 Then p = Mid$(s, i - 1, 1) Else p = ""
            If Len(p) > 0 And InStr(1, "oOgG", p, vbBinaryCompare) > 0 Then r = r & gOkina Else r = r & gTutuq
        Else
            r = r & ch
        End If
    Next i
    FixApos = r
End Function

Private Function IsForeign(ByVal w As String) As Boolean
    Dim i As Long, ch As String, nx As String
    For i = 1 To Len(w)
        ch = Mid$(w, i, 1)
        If ch = "w" Or ch = "W" Then IsForeign = True: Exit Function
        If ch = "c" Or ch = "C" Then
            nx = Mid$(w, i + 1, 1)
            If nx <> "h" And nx <> "H" Then IsForeign = True: Exit Function
        End If
    Next i
End Function

Private Function IsRoman(ByVal w As String) As Boolean
    Dim i As Long, v As Long, cur As Long, nxt As Long
    If Len(w) = 0 Or Len(w) > 15 Then Exit Function
    For i = 1 To Len(w)
        If InStr(1, "IVXLCDM", Mid$(w, i, 1), vbBinaryCompare) = 0 Then Exit Function
    Next i
    For i = 1 To Len(w)
        cur = RomanDigit(Mid$(w, i, 1))
        If i < Len(w) Then nxt = RomanDigit(Mid$(w, i + 1, 1)) Else nxt = 0
        If cur < nxt Then v = v - cur Else v = v + cur
    Next i
    If v <= 0 Or v > 4999 Then Exit Function
    IsRoman = (RomanOf(v) = w)
End Function

Private Function RomanDigit(ByVal ch As String) As Long
    Select Case ch
        Case "I": RomanDigit = 1
        Case "V": RomanDigit = 5
        Case "X": RomanDigit = 10
        Case "L": RomanDigit = 50
        Case "C": RomanDigit = 100
        Case "D": RomanDigit = 500
        Case "M": RomanDigit = 1000
    End Select
End Function

Private Function RomanOf(ByVal v As Long) As String
    Dim vals As Variant, syms As Variant, i As Long, r As String
    vals = Array(1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1)
    syms = Array("M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I")
    For i = 0 To 12
        Do While v >= vals(i)
            r = r & syms(i): v = v - vals(i)
        Loop
    Next i
    RomanOf = r
End Function

' 0 = lower, 1 = Title, 2 = UPPER, 3 = mixed
Private Function CasePattern(ByVal w As String) As Long
    Dim i As Long, ch As String, letters As Long, up As Long, firstUp As Boolean
    For i = 1 To Len(w)
        ch = Mid$(w, i, 1)
        If IsLetterCh(ch) Then
            letters = letters + 1
            If IsUpperCh(ch) Then
                up = up + 1
                If letters = 1 Then firstUp = True
            End If
        End If
    Next i
    If letters = 0 Or up = 0 Then
        CasePattern = 0
    ElseIf up = letters Then
        If letters > 1 Then CasePattern = 2 Else CasePattern = 1
    ElseIf up = 1 And firstUp Then
        CasePattern = 1
    Else
        CasePattern = 3
    End If
End Function

Private Function ApplyCase(ByVal pat As Long, ByVal s As String) As String
    Dim i As Long
    If pat = 2 Then ApplyCase = UC(s): Exit Function
    If pat = 1 Or pat = 3 Then
        For i = 1 To Len(s)
            If IsLetterCh(Mid$(s, i, 1)) Then
                ApplyCase = Left$(s, i - 1) & UC(Mid$(s, i, 1)) & Mid$(s, i + 1)
                Exit Function
            End If
        Next i
    End If
    ApplyCase = s
End Function

Private Function U16(ByVal ch As String) As Long
    If Len(ch) = 0 Then Exit Function
    U16 = AscW(ch) And &HFFFF&
End Function

Private Function IsCyrCh(ByVal ch As String) As Boolean
    Dim c As Long
    c = U16(ch)
    IsCyrCh = (c >= &H400 And c <= &H4FF)
End Function

Private Function IsLatCh(ByVal ch As String) As Boolean
    Dim c As Long
    c = U16(ch)
    IsLatCh = (c >= 65 And c <= 90) Or (c >= 97 And c <= 122)
End Function

Private Function IsApos(ByVal ch As String) As Boolean
    If Len(ch) = 0 Then Exit Function
    IsApos = (InStr(1, APOS, ch, vbBinaryCompare) > 0)
End Function

Private Function LatV(ByVal p As String) As Boolean
    If Len(p) = 0 Then Exit Function
    LatV = (InStr(1, "aeiou", p, vbBinaryCompare) > 0)
End Function

Private Function CyrVw(ByVal p As String) As Boolean
    If Len(p) = 0 Then Exit Function
    CyrVw = (InStr(1, CYRV, p, vbBinaryCompare) > 0)
End Function

Private Function IsLetterCh(ByVal ch As String) As Boolean
    If Len(ch) = 0 Then Exit Function
    IsLetterCh = (StrComp(UC(ch), LC(ch), vbBinaryCompare) <> 0)
End Function

Private Function IsUpperCh(ByVal ch As String) As Boolean
    If Not IsLetterCh(ch) Then Exit Function
    IsUpperCh = (StrComp(ch, UC(ch), vbBinaryCompare) = 0)
End Function

' Upper / lower case covering Latin and Cyrillic (incl. Uzbek letters) on every platform.
Private Function UC(ByVal s As String) As String
    Dim i As Long, c As Long, ch As String, r As String
    For i = 1 To Len(s)
        ch = Mid$(s, i, 1)
        c = U16(ch)
        Select Case c
            Case 97 To 122: ch = ChrW(c - 32)
            Case &H430 To &H44F: ch = ChrW(c - &H20)
            Case &H450 To &H45F: ch = ChrW(c - &H50)
            Case &H493, &H49B, &H4B3: ch = ChrW(c - 1)
        End Select
        r = r & ch
    Next i
    UC = r
End Function

Private Function LC(ByVal s As String) As String
    Dim i As Long, c As Long, ch As String, r As String
    For i = 1 To Len(s)
        ch = Mid$(s, i, 1)
        c = U16(ch)
        Select Case c
            Case 65 To 90: ch = ChrW(c + 32)
            Case &H410 To &H42F: ch = ChrW(c + &H20)
            Case &H400 To &H40F: ch = ChrW(c + &H50)
            Case &H492, &H49A, &H4B2: ch = ChrW(c + 1)
        End Select
        r = r & ch
    Next i
    LC = r
End Function

' Cyrillic letters <-> ASCII codes (keeps this file pure ASCII).
Private Function Enc(ByVal s As String) As String
    Dim i As Long, k As Long, ch As String, r As String
    For i = 1 To Len(s)
        ch = Mid$(s, i, 1)
        k = InStr(1, CYRSET, ch, vbBinaryCompare)
        If k > 0 Then r = r & Mid$(CODES, k, 1) Else r = r & ch
    Next i
    Enc = r
End Function

Private Function Dec(ByVal s As String) As String
    Dim i As Long, k As Long, ch As String, r As String
    For i = 1 To Len(s)
        ch = Mid$(s, i, 1)
        k = InStr(1, CODES, ch, vbBinaryCompare)
        If k > 0 Then r = r & Mid$(CYRSET, k, 1) Else r = r & ch
    Next i
    Dec = r
End Function

' "{0410}bc" -> Unicode text
Private Function UDec(ByVal s As String) As String
    Dim i As Long, j As Long, r As String, ch As String
    i = 1
    Do While i <= Len(s)
        ch = Mid$(s, i, 1)
        If ch = "{" Then
            j = InStr(i, s, "}")
            r = r & ChrW(CLng("&H" & Mid$(s, i + 1, j - i - 1)))
            i = j + 1
        Else
            r = r & ch
            i = i + 1
        End If
    Loop
    UDec = r
End Function

Private Function CGet(ByVal col As Collection, ByVal key As String, ByRef v As String) As Boolean
    On Error GoTo NotFound
    v = col(key)
    CGet = True
    Exit Function
NotFound:
    CGet = False
End Function

Private Function CHas(ByVal col As Collection, ByVal key As String) As Boolean
    Dim v As String
    CHas = CGet(col, key, v)
End Function

Private Sub CAdd(ByVal col As Collection, ByVal key As String, ByVal v As String)
    On Error Resume Next
    col.Add v, key
End Sub

' ============================== loading

Private Sub LoadAll()
    If Not gLoaded Then
        InitConsts
        Set gL2C = New Collection: Set gL2CStem = New Collection
        Set gC2L = New Collection: Set gC2LStem = New Collection
        Set gUL2C = New Collection: Set gUC2L = New Collection: Set gSkip = New Collection
        gMaxL2C = 0: gMaxC2L = 0
        LoadData
        gLoaded = True
    End If
    Select Case APOS_STYLE
        Case 2: gOkina = ChrW(&H2BB): gTutuq = ChrW(&H2BC)
        Case 3: gOkina = "'": gTutuq = "'"
        Case Else: gOkina = ChrW(&H2018): gTutuq = ChrW(&H2019)
    End Select
    LoadLugat
End Sub

Private Sub InitConsts()
    Dim i As Long
    OK = ChrW(&H2BB): TQ = ChrW(&H2BC)
    APOS = "'" & "`" & ChrW(&HB4) & ChrW(&H2018) & ChrW(&H2019) & ChrW(&H201B) & ChrW(&H2BB) & _
        ChrW(&H2BC) & ChrW(&H2B9) & ChrW(&H2BD) & ChrW(&H2032) & ChrW(&HFF07&)
    ' a b v g d e yo j z i y k l m n o p r s t u f x ts ch sh shch hard y soft e yu ya u' q g' h
    CYRSET = ""
    For i = &H430 To &H435: CYRSET = CYRSET & ChrW(i): Next i
    CYRSET = CYRSET & ChrW(&H451)
    For i = &H436 To &H44F: CYRSET = CYRSET & ChrW(i): Next i
    CYRSET = CYRSET & ChrW(&H45E) & ChrW(&H49B) & ChrW(&H493) & ChrW(&H4B3)
    cA = ChrW(&H430): cS = ChrW(&H441): cHh = ChrW(&H4B3): cSh = ChrW(&H448): cCh = ChrW(&H447)
    cU = ChrW(&H45E): cGh = ChrW(&H493): cYo = ChrW(&H451): cYu = ChrW(&H44E): cYa = ChrW(&H44F)
    cYe = ChrW(&H435): cE = ChrW(&H44D): cTs = ChrW(&H446): cHard = ChrW(&H44A): cSoft = ChrW(&H44C)
    cM = ChrW(&H43C)
    ' vowels: a e yo i o u e yu ya u'
    CYRV = ChrW(&H430) & ChrW(&H435) & ChrW(&H451) & ChrW(&H438) & ChrW(&H43E) & ChrW(&H443) & _
        ChrW(&H44D) & ChrW(&H44E) & ChrW(&H44F) & ChrW(&H45E)
    ' Latin single letters -> Cyrillic
    LATSRC = "abdfghijklmnopqrstuvxyze"
    LATDST = UDec("{0430}{0431}{0434}{0444}{0433}{04B3}{0438}{0436}{043A}{043B}{043C}{043D}" & _
        "{043E}{043F}{049B}{0440}{0441}{0442}{0443}{0432}{0445}{0439}{0437}{0435}")
    ' Cyrillic single letters -> Latin
    CYRSRC = UDec("{0430}{0431}{0432}{0433}{0434}{0436}{0437}{0438}{0439}{043A}{043B}{043C}{043D}" & _
        "{043E}{043F}{0440}{0441}{0442}{0443}{0444}{0445}{04B3}{049B}{0447}{0448}{0449}{044B}" & _
        "{044D}{0451}{044E}{044F}{044C}")
    CYRDST = Array("a", "b", "v", "g", "d", "j", "z", "i", "y", "k", "l", "m", "n", _
        "o", "p", "r", "s", "t", "u", "f", "x", "h", "q", "ch", "sh", "sh", "i", _
        "e", "yo", "yu", "ya", "")
End Sub

Private Function LugatPath() As String
    LugatPath = NormalTemplate.Path & Application.PathSeparator & LUGAT_FILE
End Function

' My dictionary: "lotin = kirill" per line, a single word = never convert.
Private Sub LoadLugat()
    Dim p As String, d As Document, t As String, stamp As String, found As Boolean
    Dim lines() As String, i As Long, ln As String, e As Long, lat As String, cyr As String
    p = LugatPath()
    On Error Resume Next
    For Each d In Documents
        If d.FullName = p Then t = d.Content.Text: found = True: Exit For
    Next d
    If Not found Then
        If Len(Dir(p)) = 0 Then
            Set gUL2C = New Collection: Set gUC2L = New Collection: Set gSkip = New Collection
            gLugatStamp = ""
            Exit Sub
        End If
        stamp = CStr(FileDateTime(p))
        If stamp = gLugatStamp Then Exit Sub
        Set d = Documents.Open(FileName:=p, ReadOnly:=True, AddToRecentFiles:=False, Visible:=False)
        t = d.Content.Text
        d.Close SaveChanges:=wdDoNotSaveChanges
        gLugatStamp = stamp
    Else
        gLugatStamp = ""
    End If
    On Error GoTo 0
    Set gUL2C = New Collection: Set gUC2L = New Collection: Set gSkip = New Collection
    lines = Split(Replace(t, vbLf, vbCr), vbCr)
    For i = LBound(lines) To UBound(lines)
        ln = Trim$(Replace(lines(i), ChrW(&HA0), " "))
        If Len(ln) > 0 And Left$(ln, 1) <> "#" Then
            e = InStr(1, ln, "=")
            If e > 0 Then
                lat = Trim$(Left$(ln, e - 1)): cyr = Trim$(Mid$(ln, e + 1))
                If Len(lat) > 0 And Len(cyr) > 0 Then
                    CAdd gUL2C, LatKey(NormLatin(lat)), LC(cyr)
                    CAdd gUC2L, Enc(LC(cyr)), LC(lat)
                End If
            Else
                CAdd gSkip, "L" & LatKey(NormLatin(ln)), "1"
                CAdd gSkip, "C" & Enc(LC(ln)), "1"
            End If
        End If
    Next i
End Sub

Private Sub AddLE(ByVal k As String, ByVal v As String)
    CAdd gL2C, k, Dec(v)
End Sub

Private Sub AddLS(ByVal k As String, ByVal v As String)
    CAdd gL2CStem, k, Dec(v)
    If Len(k) > gMaxL2C Then gMaxL2C = Len(k)
End Sub

Private Sub AddCE(ByVal k As String, ByVal v As String)
    CAdd gC2L, k, v
End Sub

Private Sub AddCS(ByVal k As String, ByVal v As String)
    CAdd gC2LStem, k, v
    If Len(Dec(k)) > gMaxC2L Then gMaxC2L = Len(Dec(k))
End Sub

' ============================== self test

Private Sub T(ByVal toLat As Boolean, ByVal inp As String, ByVal want As String)
    Dim got As String
    inp = UDec(inp): want = UDec(want)
    got = ConvertText(inp, toLat)
    gTestN = gTestN + 1
    If StrComp(got, want, vbBinaryCompare) <> 0 Then
        gTestFail = gTestFail + 1
        If Len(gTestMsg) < 900 Then gTestMsg = gTestMsg & inp & " -> " & got & " (" & want & ")" & vbCr
    End If
End Sub

'@@GENERATED@@
